# Generated by Django 5.0.6 on 2024-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
